"use client";

import { useMemo, useState } from "react";
import { Search, Plus, MoreVertical, Eye, Pencil, Users, UserCog, CheckCircle2, Clock3, XCircle, CalendarDays, X, Save, UserPlus } from "lucide-react";

type BatchStatus = "Upcoming" | "Active" | "Completed" | "Inactive";
type BatchMode = "Online" | "Offline" | "Hybrid";
type Batch = { id:string; name:string; course:string; trainer:string; students:number; maxStudents:number; startDate:string; endDate:string; mode:BatchMode; status:BatchStatus };
type BatchForm = { name:string; course:string; trainer:string; startDate:string; endDate:string; mode:BatchMode; maxStudents:string; status:BatchStatus };

const COURSES = ["Computer Basics","Typing Course - Basics","MS Office","DCA","PGDCA","AI Skills","Digital Marketing","C Programming","C++","MS DOS","HTML","Python","JAVA","Job Oriented Courses","Abacus","Spoken English"];
const EMPTY_FORM:BatchForm = { name:"",course:"",trainer:"",startDate:"",endDate:"",mode:"Offline",maxStudents:"30",status:"Upcoming" };
const INITIAL_BATCHES:Batch[] = [];

export default function BatchesPage(){
 const [batches,setBatches]=useState<Batch[]>(INITIAL_BATCHES),[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState<"All"|BatchStatus>("All");
 const [modal,setModal]=useState<"add"|"edit"|"view"|"students"|"trainer"|null>(null),[selected,setSelected]=useState<Batch|null>(null),[menu,setMenu]=useState<string|null>(null),[form,setForm]=useState<BatchForm>(EMPTY_FORM);
 const filtered=useMemo(()=>batches.filter(b=>{const q=search.toLowerCase().trim();return(!q||[b.name,b.id,b.course,b.trainer].some(v=>v.toLowerCase().includes(q)))&&(statusFilter==="All"||b.status===statusFilter)}),[batches,search,statusFilter]);
 const upcoming=batches.filter(b=>b.status==="Upcoming").length,active=batches.filter(b=>b.status==="Active").length,completed=batches.filter(b=>b.status==="Completed").length;
 const close=()=>{setModal(null);setSelected(null);setMenu(null);setForm(EMPTY_FORM)};
 const create=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!form.name.trim())return alert("Please enter batch name.");if(!form.course)return alert("Please select a course.");if(!form.startDate)return alert("Please select a start date.");if(!form.endDate)return alert("Please select an end date.");const b:Batch={id:`BAT${String(batches.length+1).padStart(3,"0")}`,name:form.name.trim(),course:form.course,trainer:form.trainer.trim()||"Not Assigned",students:0,maxStudents:Number(form.maxStudents)||30,startDate:form.startDate,endDate:form.endDate,mode:form.mode,status:form.status};setBatches(v=>[...v,b]);close()};
 const edit=(b:Batch)=>{setSelected(b);setForm({name:b.name,course:b.course,trainer:b.trainer==="Not Assigned"?"":b.trainer,startDate:b.startDate,endDate:b.endDate,mode:b.mode,maxStudents:String(b.maxStudents),status:b.status});setMenu(null);setModal("edit")};
 const update=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;if(!form.name.trim())return alert("Please enter batch name.");if(!form.course)return alert("Please select a course.");setBatches(v=>v.map(b=>b.id===selected.id?{...b,name:form.name.trim(),course:form.course,trainer:form.trainer.trim()||"Not Assigned",startDate:form.startDate,endDate:form.endDate,mode:form.mode,maxStudents:Number(form.maxStudents)||30,status:form.status}:b));close()};
 const toggle=(b:Batch)=>{setMenu(null);setBatches(v=>v.map(x=>x.id===b.id?{...x,status:x.status==="Inactive"?"Active":"Inactive"}:x))};
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1600px]">
  <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1 text-xs font-semibold text-orange-600"><CalendarDays size={14}/> Batch Management</div><h1 className="text-2xl font-bold text-[#173B67] sm:text-3xl">Batches</h1><p className="mt-1 text-sm text-slate-500">Manage course batches, trainers, students and schedules.</p></div><button onClick={()=>{setForm(EMPTY_FORM);setModal("add")}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#F97316] px-5 py-3 text-sm font-semibold text-white hover:bg-orange-600"><Plus size={18}/> Add Batch</button></header>
  <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<Users size={20}/>} title="Total Batches" value={batches.length}/><Summary icon={<Clock3 size={20}/>} title="Upcoming Batches" value={upcoming}/><Summary icon={<CheckCircle2 size={20}/>} title="Active Batches" value={active}/><Summary icon={<XCircle size={20}/>} title="Completed Batches" value={completed}/></div>
  <section className="overflow-visible rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full max-w-2xl"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by batch, ID, course or trainer..." className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-orange-400 focus:ring-2 focus:ring-orange-100"/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as "All"|BatchStatus)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-orange-400"><option>All</option><option>Upcoming</option><option>Active</option><option>Completed</option><option>Inactive</option></select></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[1100px]"><thead className="bg-slate-50"><tr>{["Batch","Batch ID","Course","Trainer","Students","Schedule","Mode","Status","Actions"].map(h=><th key={h} className="border-b border-slate-200 px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">{h}</th>)}</tr></thead><tbody>{filtered.length===0?<tr><td colSpan={9} className="px-5 py-20 text-center"><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-orange-50 text-orange-500"><CalendarDays size={27}/></div><h3 className="text-lg font-semibold text-slate-800">No batches found</h3><p className="mt-1 text-sm text-slate-500">Click “Add Batch” to create the first batch.</p></td></tr>:filtered.map(b=><tr key={b.id} className="hover:bg-slate-50"><td className="border-b border-slate-100 px-4 py-4 font-semibold text-slate-800">{b.name}</td><td className="border-b border-slate-100 px-4 py-4 text-sm text-slate-500">{b.id}</td><td className="border-b border-slate-100 px-4 py-4 text-sm">{b.course}</td><td className="border-b border-slate-100 px-4 py-4 text-sm">{b.trainer}</td><td className="border-b border-slate-100 px-4 py-4 text-sm font-medium">{b.students} / {b.maxStudents}</td><td className="border-b border-slate-100 px-4 py-4 text-sm">{formatDate(b.startDate)}<div className="mt-1 text-xs text-slate-400">to {formatDate(b.endDate)}</div></td><td className="border-b border-slate-100 px-4 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{b.mode}</span></td><td className="border-b border-slate-100 px-4 py-4"><Status status={b.status}/></td><td className="relative border-b border-slate-100 px-4 py-4"><div className="flex gap-1.5"><Action title="View" onClick={()=>{setSelected(b);setModal("view")}}><Eye size={16}/></Action><Action title="Edit" onClick={()=>edit(b)}><Pencil size={16}/></Action><Action title="More" onClick={()=>setMenu(menu===b.id?null:b.id)}><MoreVertical size={16}/></Action></div>{menu===b.id&&<div className="absolute right-4 top-14 z-50 w-56 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl"><Menu icon={<Users size={17}/>} label="Manage Students" onClick={()=>{setSelected(b);setMenu(null);setModal("students")}}/><Menu icon={<UserCog size={17}/>} label="Change Trainer" onClick={()=>{setSelected(b);setMenu(null);setModal("trainer")}}/><Menu icon={b.status==="Inactive"?<CheckCircle2 size={17}/>:<XCircle size={17}/>} label={b.status==="Inactive"?"Activate Batch":"Deactivate Batch"} onClick={()=>toggle(b)}/></div>}</td></tr>)}</tbody></table></div></section>
  <div className="mt-4 rounded-xl border border-orange-100 bg-orange-50 px-4 py-3 text-sm text-orange-800"><strong>Development mode:</strong> Batch data is currently stored locally. Student/trainer assignment will be connected to the backend later.</div>
 </div>
 {modal==="add"&&<FormModal title="Add New Batch" form={form} setForm={setForm} onClose={close} onSubmit={create} submit="Create Batch"/>}{modal==="edit"&&<FormModal title="Edit Batch" form={form} setForm={setForm} onClose={close} onSubmit={update} submit="Save Changes" edit/>}
 {modal==="view"&&selected&&<Modal title="Batch Details" subtitle="Complete batch information." close={close}><div className="mb-5 rounded-xl bg-slate-50 p-4 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-orange-100 text-orange-600"><Users size={23}/></div><div><h3 className="font-bold">{selected.name}</h3><p className="text-xs text-slate-500">{selected.id}</p></div><div className="ml-auto"><Status status={selected.status}/></div></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{[["Batch Name",selected.name],["Batch ID",selected.id],["Course",selected.course],["Trainer",selected.trainer],["Students",`${selected.students} / ${selected.maxStudents}`],["Mode",selected.mode],["Start Date",formatDate(selected.startDate)],["End Date",formatDate(selected.endDate)]].map(([l,v])=><Detail key={l} label={l} value={v}/>)}</div></Modal>}
 {modal==="students"&&selected&&<Modal title="Manage Students" subtitle={`Manage students assigned to ${selected.name}.`} close={close}><div className="rounded-xl border bg-slate-50 p-4 flex gap-3"><UserPlus className="text-orange-500"/><div><p className="font-semibold">Student assignment</p><p className="text-sm text-slate-500">{selected.students} students assigned out of {selected.maxStudents} seats.</p></div></div><p className="mt-4 text-sm text-slate-500">Student selection and batch assignment will be connected to the student database when the backend is integrated.</p></Modal>}
 {modal==="trainer"&&selected&&<Modal title="Change Trainer" subtitle={`Assign a trainer to ${selected.name}.`} close={close}><label className="mb-2 block text-sm font-semibold">Trainer</label><select value={selected.trainer==="Not Assigned"?"":selected.trainer} onChange={e=>{const trainer=e.target.value||"Not Assigned";setSelected({...selected,trainer});setBatches(v=>v.map(b=>b.id===selected.id?{...b,trainer}:b))}} className="w-full rounded-xl border px-3 py-3 text-sm"><option value="">Not Assigned</option><option>Trainer 1</option><option>Trainer 2</option><option>Trainer 3</option></select><p className="mt-3 text-sm text-slate-500">Trainer records will be loaded dynamically from the Trainers module after backend integration.</p></Modal>}
 </main>
}

function FormModal({title,form,setForm,onClose,onSubmit,submit,edit=false}:{title:string;form:BatchForm;setForm:React.Dispatch<React.SetStateAction<BatchForm>>;onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;submit:string;edit?:boolean}){const u=(k:keyof BatchForm,v:string)=>setForm(c=>({...c,[k]:v}));return <Modal title={title} subtitle="Manage batch details and schedule." close={onClose}><form onSubmit={onSubmit}><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Batch Name" value={form.name} onChange={v=>u("name",v)} required placeholder="Example: Java Morning Batch"/><Select label="Course" value={form.course} onChange={v=>u("course",v)} options={COURSES} required/><Field label="Trainer" value={form.trainer} onChange={v=>u("trainer",v)} placeholder="Enter trainer name"/><Field label="Maximum Students" type="number" value={form.maxStudents} onChange={v=>u("maxStudents",v)}/><Field label="Start Date" type="date" value={form.startDate} onChange={v=>u("startDate",v)} required/><Field label="End Date" type="date" value={form.endDate} onChange={v=>u("endDate",v)} required/><Select label="Mode" value={form.mode} onChange={v=>u("mode",v)} options={["Offline","Online","Hybrid"]}/><Select label="Status" value={form.status} onChange={v=>u("status",v)} options={["Upcoming","Active","Completed","Inactive"]}/></div><div className="mt-6 flex justify-end gap-3 border-t pt-5"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button className="inline-flex items-center gap-2 rounded-xl bg-[#F97316] px-5 py-2.5 text-sm font-semibold text-white">{edit?<Save size={17}/>:<Plus size={17}/>} {submit}</button></div></form></Modal>}
function Modal({title,subtitle,children,close}:{title:string;subtitle:string;children:React.ReactNode;close:()=>void}){return <div className="fixed inset-0 z-[1000] flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b p-5 sm:p-6"><div><h2 className="text-xl font-bold text-[#173B67]">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><button onClick={close} className="rounded-lg bg-slate-100 p-2"><X size={18}/></button></div><div className="p-5 sm:p-6">{children}</div></div></div>}
function Field({label,value,onChange,placeholder,type="text",required=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string;required?:boolean}){return <div><label className="mb-2 block text-sm font-semibold">{label}{required&&<span className="text-red-500"> *</span>}</label><input type={type} required={required} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-orange-400"/></div>}
function Select({label,value,onChange,options,required=false}:{label:string;value:string;onChange:(v:string)=>void;options:string[];required?:boolean}){return <div><label className="mb-2 block text-sm font-semibold">{label}{required&&<span className="text-red-500"> *</span>}</label><select required={required} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm outline-none focus:border-orange-400"><option value="">Select {label.toLowerCase()}</option>{options.map(o=><option key={o}>{o}</option>)}</select></div>}
function Summary({icon,title,value}:{icon:React.ReactNode;title:string;value:number}){return <div className="flex items-center gap-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-orange-500">{icon}</div><div><div className="text-2xl font-bold text-[#173B67]">{value}</div><div className="text-sm text-slate-500">{title}</div></div></div>}
function Status({status}:{status:BatchStatus}){const c={Upcoming:"bg-amber-50 text-amber-700",Active:"bg-emerald-50 text-emerald-700",Completed:"bg-indigo-50 text-indigo-700",Inactive:"bg-red-50 text-red-700"};return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${c[status]}`}>{status}</span>}
function Action({children,title,onClick}:{children:React.ReactNode;title:string;onClick:()=>void}){return <button type="button" title={title} onClick={onClick} className="flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-slate-500 hover:border-orange-200 hover:bg-orange-50 hover:text-orange-600">{children}</button>}
function Menu({icon,label,onClick}:{icon:React.ReactNode;label:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium text-slate-700 hover:bg-slate-50">{icon}{label}</button>}
function Detail({label,value}:{label:string;value:string}){return <div className="rounded-xl border p-3"><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-medium text-slate-800">{value}</p></div>}
function formatDate(date:string){if(!date)return "Not set";const d=new Date(`${date}T00:00:00`);return Number.isNaN(d.getTime())?date:d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}
