import { Course, Trainer, Testimonial } from "@/types";

export const MOCK_COURSES: Course[] = [
  {
    id: "computer-basics",
    slug: "computer-basics",
    title: "Computer Basics",
    mode: "Online",
    description:
      "Learn essential computer operations, internet usage, file management, and everyday digital skills.",
    durationMonths: 2,
    modules: 10,
    enrolled: 120,
    price: 5000,
    accentColor: "border-t-blue-500",
    language: "English",
    totalVideos: 15,
    hasCertificate: true,
    aboutLong:
      "A beginner-friendly course covering essential computer concepts and practical everyday computer usage.",
    whatYouWillLearn: [
      "Computer fundamentals",
      "Windows and file management",
      "Internet and email usage",
      "Basic troubleshooting",
    ],
    requirements: [
      "Basic literacy",
      "No prior computer experience required",
    ],
    topics: [
      {
        title: "Module 1: Computer Fundamentals",
        lessons: [
          "Introduction to computers",
          "Hardware and software",
          "Windows basics",
        ],
      },
      {
        title: "Module 2: Internet & Digital Skills",
        lessons: [
          "Internet browsing",
          "Email basics",
          "File management",
        ],
      },
    ],
    instructor: {
      name: "Rajesh Kumar",
      title: "Computer Trainer",
      avatarUrl: "/trainers/rajesh.jpg.svg",
      bio: "Experienced trainer focused on practical computer education.",
    },
  },

  {
    id: "ai-skills",
    slug: "ai-skills",
    title: "AI Skills",
    mode: "Online",
    description:
      "Learn practical AI concepts, generative AI tools, prompt engineering, and AI-assisted productivity.",
    durationMonths: 3,
    modules: 14,
    enrolled: 130,
    price: 15000,
    accentColor: "border-t-cyan-500",
    language: "English",
    totalVideos: 25,
    hasCertificate: true,
    aboutLong:
      "Develop practical artificial intelligence skills for education, business, programming, and everyday productivity.",
    whatYouWillLearn: [
      "AI fundamentals",
      "Generative AI",
      "Prompt engineering",
      "AI productivity tools",
    ],
    requirements: ["Basic computer and internet skills"],
    topics: [
      {
        title: "Module 1: AI Fundamentals",
        lessons: [
          "Introduction to AI",
          "Machine learning basics",
          "Generative AI",
        ],
      },
      {
        title: "Module 2: Practical AI",
        lessons: [
          "Prompt engineering",
          "AI tools",
          "AI-assisted productivity",
        ],
      },
    ],
    instructor: {
      name: "Priya Sharma",
      title: "AI & Technology Trainer",
      avatarUrl: "/trainers/priya.jpg.svg",
      bio: "Technology trainer focused on practical AI skills and modern digital tools.",
    },
  },

  {
    id: "digital-marketing",
    slug: "digital-marketing",
    title: "Digital Marketing",
    mode: "online",
    description:
      "Learn SEO, social media marketing, Google Ads, content marketing, and digital analytics.",
    durationMonths: 3,
    modules: 14,
    enrolled: 88,
    price: 22000,
    accentColor: "border-t-pink-500",
    language: "English",
    totalVideos: 26,
    hasCertificate: true,
    aboutLong:
      "Build practical digital marketing skills covering search, social media, advertising, content, and analytics.",
    whatYouWillLearn: [
      "SEO",
      "Social media marketing",
      "Google Ads",
      "Content marketing",
      "Digital analytics",
    ],
    requirements: ["Basic computer and internet skills"],
    topics: [
      {
        title: "Module 1: Digital Marketing Foundations",
        lessons: [
          "Digital marketing basics",
          "SEO",
          "Content marketing",
        ],
      },
      {
        title: "Module 2: Advertising & Analytics",
        lessons: [
          "Google Ads",
          "Social media advertising",
          "Analytics",
        ],
      },
    ],
    instructor: {
      name: "Meera Patel",
      title: "Digital Marketing Trainer",
      avatarUrl: "/trainers/meera.jpg.svg",
      bio: "Digital marketing trainer focused on practical campaigns and analytics.",
    },
  },

  {
    id: "c-programming",
    slug: "c-programming",
    title: "C Programming",
    mode: "Online",
    description:
      "Learn C programming fundamentals, problem solving, functions, arrays, pointers, and data structures.",
    durationMonths: 2,
    modules: 12,
    enrolled: 75,
    price: 7000,
    accentColor: "border-t-blue-500",
    language: "English",
    totalVideos: 20,
    hasCertificate: true,
    aboutLong:
      "A practical introduction to C programming and fundamental programming concepts.",
    whatYouWillLearn: [
      "C syntax and data types",
      "Control statements",
      "Functions and arrays",
      "Pointers",
      "Basic data structures",
    ],
    requirements: ["Basic computer knowledge"],
    topics: [
      {
        title: "Module 1: C Fundamentals",
        lessons: [
          "Syntax",
          "Variables",
          "Operators",
          "Control statements",
        ],
      },
      {
        title: "Module 2: Programming Concepts",
        lessons: [
          "Functions",
          "Arrays",
          "Pointers",
        ],
      },
    ],
    instructor: {
      name: "Rajesh Kumar",
      title: "Programming Trainer",
      avatarUrl: "/trainers/rajesh.jpg.svg",
      bio: "Programming trainer focused on strong fundamentals and practical coding.",
    },
  },

  {
    id: "cpp",
    slug: "cpp",
    title: "C++",
    mode: "Online",
    description:
      "Master C++ programming, object-oriented programming, STL, and practical application development.",
    durationMonths: 3,
    modules: 15,
    enrolled: 70,
    price: 9000,
    accentColor: "border-t-indigo-500",
    language: "English",
    totalVideos: 25,
    hasCertificate: true,
    aboutLong:
      "Learn modern C++ programming with a strong focus on object-oriented programming and problem solving.",
    whatYouWillLearn: [
      "C++ fundamentals",
      "Object-oriented programming",
      "STL",
      "Exception handling",
      "Problem solving",
    ],
    requirements: ["Basic programming knowledge recommended"],
    topics: [
      {
        title: "Module 1: C++ Fundamentals",
        lessons: [
          "Syntax",
          "Classes and objects",
          "Functions",
        ],
      },
      {
        title: "Module 2: OOP & STL",
        lessons: [
          "Inheritance",
          "Polymorphism",
          "STL",
        ],
      },
    ],
    instructor: {
      name: "Rajesh Kumar",
      title: "Programming Trainer",
      avatarUrl: "/trainers/rajesh.jpg.svg",
      bio: "Programming trainer focused on practical software development.",
    },
  },

  {
    id: "html",
    slug: "html",
    title: "HTML",
    mode: "Online",
    description:
      "Learn HTML from fundamentals to building structured and responsive web pages.",
    durationMonths: 1,
    modules: 8,
    enrolled: 90,
    price: 4000,
    accentColor: "border-t-orange-500",
    language: "English",
    totalVideos: 12,
    hasCertificate: true,
    aboutLong:
      "Learn HTML fundamentals and build the foundation required for modern web development.",
    whatYouWillLearn: [
      "HTML structure",
      "Forms",
      "Tables",
      "Links and media",
      "Semantic HTML",
    ],
    requirements: ["Basic computer knowledge"],
    topics: [
      {
        title: "Module 1: HTML Fundamentals",
        lessons: [
          "HTML structure",
          "Elements and attributes",
          "Links and images",
        ],
      },
      {
        title: "Module 2: Forms & Layout",
        lessons: [
          "Forms",
          "Tables",
          "Semantic HTML",
        ],
      },
    ],
    instructor: {
      name: "Rajesh Kumar",
      title: "Web Development Trainer",
      avatarUrl: "/trainers/rajesh.jpg.svg",
      bio: "Web development trainer focused on practical front-end skills.",
    },
  },

  {
    id: "python",
    slug: "python",
    title: "Python",
    mode: "Online",
    description:
      "Learn Python programming from basics through functions, modules, object-oriented programming, and projects.",
    durationMonths: 3,
    modules: 16,
    enrolled: 125,
    price: 12000,
    accentColor: "border-t-yellow-500",
    language: "English",
    totalVideos: 28,
    hasCertificate: true,
    aboutLong:
      "A practical Python programming course designed to build strong programming fundamentals.",
    whatYouWillLearn: [
      "Python fundamentals",
      "Functions and modules",
      "Object-oriented programming",
      "File handling",
      "Python projects",
    ],
    requirements: ["Basic computer and internet skills"],
    topics: [
      {
        title: "Module 1: Python Basics",
        lessons: [
          "Syntax",
          "Data types",
          "Control flow",
        ],
      },
      {
        title: "Module 2: Python Programming",
        lessons: [
          "Functions",
          "Modules",
          "OOP",
          "File handling",
        ],
      },
    ],
    instructor: {
      name: "Priya Sharma",
      title: "Python Trainer",
      avatarUrl: "/trainers/priya.jpg.svg",
      bio: "Technology trainer specializing in Python and data-related skills.",
    },
  },

  {
    id: "java",
    slug: "java",
    title: "JAVA",
    mode: "Online",
    description:
      "Learn Java programming, object-oriented concepts, collections, exception handling, and application development.",
    durationMonths: 4,
    modules: 20,
    enrolled: 100,
    price: 15000,
    accentColor: "border-t-red-500",
    language: "English",
    totalVideos: 35,
    hasCertificate: true,
    aboutLong:
      "Build a strong foundation in Java programming and object-oriented application development.",
    whatYouWillLearn: [
      "Java fundamentals",
      "Object-oriented programming",
      "Collections",
      "Exception handling",
      "Java application development",
    ],
    requirements: ["Basic programming knowledge recommended"],
    topics: [
      {
        title: "Module 1: Java Fundamentals",
        lessons: [
          "Syntax",
          "Data types",
          "Control statements",
        ],
      },
      {
        title: "Module 2: Object-Oriented Java",
        lessons: [
          "Classes",
          "Inheritance",
          "Polymorphism",
          "Collections",
        ],
      },
    ],
    instructor: {
      name: "Rajesh Kumar",
      title: "Java Trainer",
      avatarUrl: "/trainers/rajesh.jpg.svg",
      bio: "Programming trainer focused on Java and application development.",
    },
  },

  {
    id: "abacus",
    slug: "abacus",
    title: "Abacus",
    mode: "Online",
    description:
      "Develop calculation speed, concentration, memory, and numerical skills through Abacus training.",
    durationMonths: 3,
    modules: 10,
    enrolled: 65,
    price: 6000,
    accentColor: "border-t-emerald-500",
    language: "English",
    totalVideos: 15,
    hasCertificate: true,
    aboutLong:
      "A structured Abacus program designed to improve numerical ability, concentration, and mental calculation.",
    whatYouWillLearn: [
      "Abacus fundamentals",
      "Mental calculation",
      "Number skills",
      "Calculation speed",
    ],
    requirements: ["Suitable for beginners"],
    topics: [
      {
        title: "Module 1: Abacus Fundamentals",
        lessons: [
          "Introduction to Abacus",
          "Basic calculations",
          "Number recognition",
        ],
      },
      {
        title: "Module 2: Mental Mathematics",
        lessons: [
          "Mental calculation",
          "Speed practice",
          "Advanced exercises",
        ],
      },
    ],
    instructor: {
      name: "Meera Patel",
      title: "Abacus Trainer",
      avatarUrl: "/trainers/meera.jpg.svg",
      bio: "Trainer focused on practical learning and skill development.",
    },
  },

  {
    id: "spoken-english",
    slug: "spoken-english",
    title: "Spoken English",
    mode: "Online",
    description:
      "Improve spoken English, grammar, vocabulary, pronunciation, and confidence for everyday and professional communication.",
    durationMonths: 3,
    modules: 12,
    enrolled: 100,
    price: 8000,
    accentColor: "border-t-pink-500",
    language: "English",
    totalVideos: 20,
    hasCertificate: true,
    aboutLong:
      "A practical communication program designed to improve English speaking ability and confidence.",
    whatYouWillLearn: [
      "Everyday English",
      "Grammar fundamentals",
      "Vocabulary building",
      "Conversation skills",
      "Interview communication",
    ],
    requirements: ["Basic understanding of English"],
    topics: [
      {
        title: "Module 1: English Fundamentals",
        lessons: [
          "Grammar basics",
          "Vocabulary",
          "Sentence formation",
        ],
      },
      {
        title: "Module 2: Communication Skills",
        lessons: [
          "Daily conversations",
          "Public speaking",
          "Interview communication",
        ],
      },
    ],
    instructor: {
      name: "Meera Patel",
      title: "Communication Trainer",
      avatarUrl: "/trainers/meera.jpg.svg",
      bio: "Trainer focused on communication, confidence, and professional English.",
    },
  },
  {
    id: "handwriting",
    slug: "handwriting",
    title: "Handwriting",
    mode: "Online",
    description: "Improve handwriting quality, presentation, writing speed, and neatness through guided practice.",
    durationMonths: 2,
    modules: 8,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-orange-500",
    language: "English",
    totalVideos: 10,
    hasCertificate: true,
    aboutLong: "A practical handwriting course focused on clear, neat, and confident writing.",
    whatYouWillLearn: ["Letter formation", "Neat writing", "Writing speed", "Presentation skills"],
    requirements: ["Suitable for beginners"],
    topics: [{ title: "Module 1: Handwriting Fundamentals", lessons: ["Letter formation", "Spacing", "Writing practice"] }],
    instructor: { name: "Meera Patel", title: "Skill Development Trainer", avatarUrl: "/trainers/meera.jpg.svg", bio: "Trainer focused on practical learning and skill development." },
  },
  {
    id: "typing-basics",
    slug: "typing-basics",
    title: "Typing Basics",
    mode: "Online",
    description: "Build keyboard familiarity, typing accuracy, and basic typing speed through structured practice.",
    durationMonths: 1,
    modules: 6,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-blue-500",
    language: "English",
    totalVideos: 10,
    hasCertificate: true,
    aboutLong: "A beginner-friendly typing program for developing accurate and comfortable keyboard skills.",
    whatYouWillLearn: ["Keyboard layout", "Finger positioning", "Typing accuracy", "Basic speed practice"],
    requirements: ["Basic computer knowledge"],
    topics: [{ title: "Module 1: Typing Fundamentals", lessons: ["Keyboard layout", "Finger positioning", "Typing exercises"] }],
    instructor: { name: "Rajesh Kumar", title: "Computer Trainer", avatarUrl: "/trainers/rajesh.jpg.svg", bio: "Experienced trainer focused on practical computer skills." },
  },
  {
    id: "focus-on-education",
    slug: "focus-on-education",
    title: "How to Focus on Education",
    mode: "Online",
    description: "Develop practical study habits, focus techniques, time management, and learning discipline.",
    durationMonths: 1,
    modules: 5,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-emerald-500",
    language: "English",
    totalVideos: 8,
    hasCertificate: true,
    aboutLong: "A practical learning-skills course designed to improve focus, consistency, and study habits.",
    whatYouWillLearn: ["Focus techniques", "Study planning", "Time management", "Learning habits"],
    requirements: ["Suitable for students"],
    topics: [{ title: "Module 1: Learning & Focus", lessons: ["Setting goals", "Managing distractions", "Study planning"] }],
    instructor: { name: "Meera Patel", title: "Skill Development Trainer", avatarUrl: "/trainers/meera.jpg.svg", bio: "Trainer focused on practical learning and skill development." },
  },
  {
    id: "ms-word",
    slug: "ms-word",
    title: "MS Word",
    mode: "Online",
    description: "Learn Microsoft Word for document creation, formatting, tables, layouts, and professional documents.",
    durationMonths: 1,
    modules: 8,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-blue-500",
    language: "English",
    totalVideos: 12,
    hasCertificate: true,
    aboutLong: "Practical Microsoft Word training for creating and formatting professional documents.",
    whatYouWillLearn: ["Document creation", "Formatting", "Tables", "Page layouts"],
    requirements: ["Basic computer knowledge"],
    topics: [{ title: "Module 1: Word Fundamentals", lessons: ["Creating documents", "Formatting", "Tables and layouts"] }],
    instructor: { name: "Rajesh Kumar", title: "Computer Trainer", avatarUrl: "/trainers/rajesh.jpg.svg", bio: "Experienced trainer focused on practical computer education." },
  },
  {
    id: "ms-excel",
    slug: "ms-excel",
    title: "MS Excel",
    mode: "Online",
    description: "Learn spreadsheets, formulas, functions, charts, data handling, and practical Excel skills.",
    durationMonths: 2,
    modules: 10,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-emerald-500",
    language: "English",
    totalVideos: 15,
    hasCertificate: true,
    aboutLong: "Practical Excel training covering spreadsheet management, formulas, functions, and data presentation.",
    whatYouWillLearn: ["Worksheets", "Formulas and functions", "Charts", "Data management"],
    requirements: ["Basic computer knowledge"],
    topics: [{ title: "Module 1: Excel Fundamentals", lessons: ["Worksheets", "Formulas", "Functions", "Charts"] }],
    instructor: { name: "Rajesh Kumar", title: "Computer Trainer", avatarUrl: "/trainers/rajesh.jpg.svg", bio: "Experienced trainer focused on practical office skills." },
  },
  {
    id: "ms-powerpoint",
    slug: "ms-powerpoint",
    title: "MS PowerPoint",
    mode: "Online",
    description: "Create professional presentations using slides, layouts, animations, images, and presentation tools.",
    durationMonths: 1,
    modules: 7,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-orange-500",
    language: "English",
    totalVideos: 10,
    hasCertificate: true,
    aboutLong: "Learn to create clear, engaging, and professional PowerPoint presentations.",
    whatYouWillLearn: ["Slide creation", "Layouts", "Animations", "Presentation design"],
    requirements: ["Basic computer knowledge"],
    topics: [{ title: "Module 1: Presentations", lessons: ["Slides", "Layouts", "Images", "Animations"] }],
    instructor: { name: "Rajesh Kumar", title: "Computer Trainer", avatarUrl: "/trainers/rajesh.jpg.svg", bio: "Experienced trainer focused on practical office skills." },
  },
  {
    id: "windows",
    slug: "windows",
    title: "Windows",
    mode: "Online",
    description: "Learn Windows basics, settings, file management, applications, and everyday operating-system skills.",
    durationMonths: 1,
    modules: 6,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-cyan-500",
    language: "English",
    totalVideos: 10,
    hasCertificate: true,
    aboutLong: "Build confidence using Windows for everyday computer tasks and file management.",
    whatYouWillLearn: ["Windows interface", "Files and folders", "Settings", "Applications"],
    requirements: ["Suitable for beginners"],
    topics: [{ title: "Module 1: Windows Fundamentals", lessons: ["Desktop", "Files and folders", "Settings"] }],
    instructor: { name: "Rajesh Kumar", title: "Computer Trainer", avatarUrl: "/trainers/rajesh.jpg.svg", bio: "Experienced trainer focused on practical computer skills." },
  },
  {
    id: "data-structures",
    slug: "data-structures",
    title: "Data Structures",
    mode: "Online",
    description: "Learn fundamental data structures, algorithms, problem solving, and efficient data organization.",
    durationMonths: 3,
    modules: 12,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-indigo-500",
    language: "English",
    totalVideos: 20,
    hasCertificate: true,
    aboutLong: "A practical introduction to core data structures and algorithmic problem solving.",
    whatYouWillLearn: ["Arrays", "Linked lists", "Stacks and queues", "Trees and algorithms"],
    requirements: ["Basic programming knowledge recommended"],
    topics: [{ title: "Module 1: Data Structures Fundamentals", lessons: ["Arrays", "Linked lists", "Stacks", "Queues"] }],
    instructor: { name: "Rajesh Kumar", title: "Programming Trainer", avatarUrl: "/trainers/rajesh.jpg.svg", bio: "Programming trainer focused on strong fundamentals and practical coding." },
  },
  {
    id: "power-bi",
    slug: "power-bi",
    title: "Power BI",
    mode: "Online",
    description: "Learn data visualization, dashboards, reports, data modeling, and practical Power BI skills.",
    durationMonths: 2,
    modules: 10,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-yellow-500",
    language: "English",
    totalVideos: 16,
    hasCertificate: true,
    aboutLong: "Practical Power BI training for creating interactive reports and business dashboards.",
    whatYouWillLearn: ["Data import", "Data modeling", "Visualizations", "Interactive dashboards"],
    requirements: ["Basic computer knowledge"],
    topics: [{ title: "Module 1: Power BI Fundamentals", lessons: ["Data import", "Data modeling", "Charts", "Dashboards"] }],
    instructor: { name: "Priya Sharma", title: "Data & Technology Trainer", avatarUrl: "/trainers/priya.jpg.svg", bio: "Technology trainer focused on practical digital and data skills." },
  },
  {
    id: "tally",
    slug: "tally",
    title: "Tally",
    mode: "Online",
    description: "Learn practical accounting, company setup, vouchers, ledgers, and business bookkeeping using Tally.",
    durationMonths: 2,
    modules: 10,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-blue-500",
    language: "English",
    totalVideos: 16,
    hasCertificate: true,
    aboutLong: "Practical Tally training focused on everyday accounting and business bookkeeping tasks.",
    whatYouWillLearn: ["Company creation", "Ledgers", "Vouchers", "Reports"],
    requirements: ["Basic computer knowledge"],
    topics: [{ title: "Module 1: Tally Fundamentals", lessons: ["Company setup", "Ledgers", "Vouchers", "Reports"] }],
    instructor: { name: "Meera Patel", title: "Business Skills Trainer", avatarUrl: "/trainers/meera.jpg.svg", bio: "Trainer focused on practical business and digital skills." },
  },
  {
    id: "affiliate-marketing",
    slug: "affiliate-marketing",
    title: "Affiliate Marketing",
    mode: "Online",
    description: "Learn affiliate marketing fundamentals, content strategies, platforms, promotion, and performance tracking.",
    durationMonths: 2,
    modules: 8,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-pink-500",
    language: "English",
    totalVideos: 12,
    hasCertificate: true,
    aboutLong: "Learn the fundamentals of affiliate marketing and practical methods for promoting products online.",
    whatYouWillLearn: ["Affiliate basics", "Content promotion", "Tracking", "Campaign planning"],
    requirements: ["Basic computer and internet skills"],
    topics: [{ title: "Module 1: Affiliate Marketing", lessons: ["Affiliate basics", "Platforms", "Promotion", "Tracking"] }],
    instructor: { name: "Meera Patel", title: "Digital Marketing Trainer", avatarUrl: "/trainers/meera.jpg.svg", bio: "Digital marketing trainer focused on practical online skills." },
  },
  {
    id: "free-launching-projects",
    slug: "free-launching-projects",
    title: "Free Launching Projects",
    mode: "online",
    description: "Practice launching practical projects with guidance from planning through basic deployment and presentation.",
    durationMonths: 2,
    modules: 8,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-orange-500",
    language: "English",
    totalVideos: 12,
    hasCertificate: true,
    aboutLong: "A practical project-based learning program focused on turning ideas into presentable projects.",
    whatYouWillLearn: ["Project planning", "Practical implementation", "Testing", "Project presentation"],
    requirements: ["Basic computer knowledge"],
    topics: [{ title: "Module 1: Project Launch", lessons: ["Planning", "Implementation", "Testing", "Presentation"] }],
    instructor: { name: "Rajesh Kumar", title: "Lead Trainer", avatarUrl: "/trainers/rajesh.jpg.svg", bio: "Experienced trainer focused on practical and career-oriented education." },
  },
  {
    id: "data-entry",
    slug: "data-entry",
    title: "Data Entry",
    mode: "Online",
    description: "Build practical data entry skills including typing, spreadsheet entry, accuracy, and digital record handling.",
    durationMonths: 1,
    modules: 6,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-emerald-500",
    language: "English",
    totalVideos: 10,
    hasCertificate: true,
    aboutLong: "Practical training for accurate and efficient data entry and digital record handling.",
    whatYouWillLearn: ["Data entry basics", "Typing accuracy", "Spreadsheet entry", "Record management"],
    requirements: ["Basic computer knowledge"],
    topics: [{ title: "Module 1: Data Entry Fundamentals", lessons: ["Data entry", "Accuracy", "Spreadsheets", "Records"] }],
    instructor: { name: "Meera Patel", title: "Computer Trainer", avatarUrl: "/trainers/meera.jpg.svg", bio: "Trainer focused on practical digital skills." },
  },
  {
    id: "interview-preparation",
    slug: "interview-preparation",
    title: "Interview Preparation",
    mode: "online",
    description: "Prepare for interviews with communication practice, resume guidance, common questions, and confidence building.",
    durationMonths: 1,
    modules: 6,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-indigo-500",
    language: "English",
    totalVideos: 10,
    hasCertificate: true,
    aboutLong: "A practical interview-readiness program covering communication, preparation, and confidence.",
    whatYouWillLearn: ["Interview communication", "Resume preparation", "Common questions", "Confidence building"],
    requirements: ["Suitable for job seekers"],
    topics: [{ title: "Module 1: Interview Readiness", lessons: ["Resume preparation", "Interview questions", "Communication", "Mock practice"] }],
    instructor: { name: "Meera Patel", title: "Career Skills Trainer", avatarUrl: "/trainers/meera.jpg.svg", bio: "Trainer focused on communication and professional skills." },
  },
  {
    id: "online-work-skills",
    slug: "online-work-skills",
    title: "Online Work Skills",
    mode: "Online",
    description: "Learn essential digital skills for working online, communicating remotely, managing tasks, and using online tools.",
    durationMonths: 2,
    modules: 8,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-cyan-500",
    language: "English",
    totalVideos: 12,
    hasCertificate: true,
    aboutLong: "Practical digital skills for working, communicating, and managing tasks in online environments.",
    whatYouWillLearn: ["Online tools", "Remote communication", "Task management", "Digital work practices"],
    requirements: ["Basic computer and internet skills"],
    topics: [{ title: "Module 1: Online Work", lessons: ["Online tools", "Communication", "Task management", "Digital practices"] }],
    instructor: { name: "Priya Sharma", title: "Technology Trainer", avatarUrl: "/trainers/priya.jpg.svg", bio: "Technology trainer focused on practical digital skills." },
  },
  {
    id: "digital-payments",
    slug: "digital-payments",
    title: "Digital Payments",
    mode: "Online",
    description: "Understand practical digital payment methods, online transactions, payment safety, and everyday digital finance.",
    durationMonths: 1,
    modules: 5,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-orange-500",
    language: "English",
    totalVideos: 8,
    hasCertificate: true,
    aboutLong: "Learn practical digital payment methods and safe everyday online transaction practices.",
    whatYouWillLearn: ["Digital payment methods", "Online transactions", "Payment safety", "Basic troubleshooting"],
    requirements: ["Basic smartphone or computer knowledge"],
    topics: [{ title: "Module 1: Digital Payments", lessons: ["Payment methods", "Online transactions", "Safety", "Troubleshooting"] }],
    instructor: { name: "Priya Sharma", title: "Digital Skills Trainer", avatarUrl: "/trainers/priya.jpg.svg", bio: "Trainer focused on practical digital skills." },
  },
  {
    id: "internet-email",
    slug: "internet-email",
    title: "Internet & Email",
    mode: "Online",
    description: "Learn internet browsing, email communication, online searches, attachments, and safe digital communication.",
    durationMonths: 1,
    modules: 6,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-blue-500",
    language: "English",
    totalVideos: 10,
    hasCertificate: true,
    aboutLong: "A beginner-friendly course covering essential internet and email skills for everyday digital communication.",
    whatYouWillLearn: ["Web browsing", "Email", "Attachments", "Online safety"],
    requirements: ["Suitable for beginners"],
    topics: [{ title: "Module 1: Internet & Email Fundamentals", lessons: ["Browsing", "Email basics", "Attachments", "Safety"] }],
    instructor: { name: "Rajesh Kumar", title: "Computer Trainer", avatarUrl: "/trainers/rajesh.jpg.svg", bio: "Experienced trainer focused on practical computer skills." },
  },
  {
    id: "home-business-ideas",
    slug: "home-business-ideas",
    title: "Home Business Ideas",
    mode: "Online",
    description: "Explore practical ideas for starting and managing small home-based digital businesses and services.",
    durationMonths: 1,
    modules: 6,
    enrolled: 0,
    price: 0,
    accentColor: "border-t-pink-500",
    language: "English",
    totalVideos: 10,
    hasCertificate: true,
    aboutLong: "A practical introduction to home-based business opportunities, planning, and digital support skills.",
    whatYouWillLearn: ["Business idea planning", "Basic digital promotion", "Online work models", "Getting started"],
    requirements: ["Basic computer and internet skills"],
    topics: [{ title: "Module 1: Home Business Fundamentals", lessons: ["Business ideas", "Planning", "Digital promotion", "Getting started"] }],
    instructor: { name: "Meera Patel", title: "Business Skills Trainer", avatarUrl: "/trainers/meera.jpg.svg", bio: "Trainer focused on practical business and digital skills." },
  },

];

export const MOCK_TRAINERS: Trainer[] = [
  {
    id: "t1",
    name: "Rajesh Kumar",
    yearsExperience: 8,
    avatarUrl: "/trainers/rajesh.jpg.svg",
    specialty: "Computer & Programming",
  },
  {
    id: "t2",
    name: "Priya Sharma",
    yearsExperience: 6,
    avatarUrl: "/trainers/priya.jpg.svg",
    specialty: "Python & AI Skills",
  },
  {
    id: "t3",
    name: "Anand Verma",
    yearsExperience: 10,
    avatarUrl: "/trainers/anand.jpg.svg",
    specialty: "SAP Training",
  },
  {
    id: "t4",
    name: "Meera Patel",
    yearsExperience: 5,
    avatarUrl: "/trainers/meera.jpg.svg",
    specialty: "Digital Marketing & Communication",
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "r1",
    studentName: "Ravi Teja",
    initials: "RT",
    course: "Computer Basics",
    rating: 5,
    quote:
      "The training was very practical and easy to understand. I gained confidence in using computers and learned many useful skills.",
  },
  {
    id: "r2",
    studentName: "Anjali Sharma",
    initials: "AS",
    course: "Python",
    rating: 5,
    quote:
      "The Python training was explained clearly with practical examples. The trainer was very supportive throughout the course.",
  },
  {
    id: "r3",
    studentName: "Mohammed Farhan",
    initials: "MF",
    course: "AI Skills",
    rating: 5,
    quote:
      "The AI Skills course helped me understand modern AI tools and how to use them effectively in real-world situations.",
  },
];